[package]
name = "hir"
description = "Rule-aware, game-independent semantic lowering boundary for ParadoxCode."
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
publish = false

[dependencies]
rustc-hash = "2"
parser = { path = "../parser" }
rules = { path = "../rules" }
text = { path = "../text" }

[lints]
workspace = true

[dev-dependencies]
game = { path = "../game" }
