[workspace]
resolver = "2"
members = [
    "crates/pdx-text",
    "crates/pdx-syntax",
    "crates/pdx-rules",
    "crates/pdx-game-eu4",
    "crates/pdx-eu4",
    "crates/pdx-rulec",
    "crates/pdx-hir",
    "crates/pdx-workspace",
    "crates/pdx-analysis",
    "crates/pdx-format",
    "crates/pdx-lsp",
    "crates/pdx-cli",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
rust-version = "1.88"
authors = ["ParadoxCode contributors"]
homepage = "https://github.com/danxiaogu520/ParadoxCode"
repository = "https://github.com/danxiaogu520/ParadoxCode"
readme = "README.md"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"
