/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 19
#define LARGE_STATE_COUNT 5
#define SYMBOL_COUNT 17
#define ALIAS_COUNT 0
#define TOKEN_COUNT 9
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_COMMA = 1,
  anon_sym_SEMI = 2,
  anon_sym_TAB = 3,
  anon_sym_DQUOTE = 4,
  aux_sym_quoted_cell_token1 = 5,
  sym_escaped_quote = 6,
  sym_unquoted_cell = 7,
  sym_newline = 8,
  sym_source_file = 9,
  sym_record = 10,
  sym_delimiter = 11,
  sym_cell = 12,
  sym_quoted_cell = 13,
  aux_sym_source_file_repeat1 = 14,
  aux_sym_record_repeat1 = 15,
  aux_sym_quoted_cell_repeat1 = 16,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COMMA] = ",",
  [anon_sym_SEMI] = ";",
  [anon_sym_TAB] = "\t",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_cell_token1] = "quoted_cell_token1",
  [sym_escaped_quote] = "escaped_quote",
  [sym_unquoted_cell] = "unquoted_cell",
  [sym_newline] = "newline",
  [sym_source_file] = "source_file",
  [sym_record] = "record",
  [sym_delimiter] = "delimiter",
  [sym_cell] = "cell",
  [sym_quoted_cell] = "quoted_cell",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_record_repeat1] = "record_repeat1",
  [aux_sym_quoted_cell_repeat1] = "quoted_cell_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_TAB] = anon_sym_TAB,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_cell_token1] = aux_sym_quoted_cell_token1,
  [sym_escaped_quote] = sym_escaped_quote,
  [sym_unquoted_cell] = sym_unquoted_cell,
  [sym_newline] = sym_newline,
  [sym_source_file] = sym_source_file,
  [sym_record] = sym_record,
  [sym_delimiter] = sym_delimiter,
  [sym_cell] = sym_cell,
  [sym_quoted_cell] = sym_quoted_cell,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_record_repeat1] = aux_sym_record_repeat1,
  [aux_sym_quoted_cell_repeat1] = aux_sym_quoted_cell_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TAB] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_cell_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escaped_quote] = {
    .visible = true,
    .named = true,
  },
  [sym_unquoted_cell] = {
    .visible = true,
    .named = true,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_record] = {
    .visible = true,
    .named = true,
  },
  [sym_delimiter] = {
    .visible = true,
    .named = true,
  },
  [sym_cell] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_cell] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_record_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_cell_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      ADVANCE_MAP(
        '\t', 11,
        '\n', 21,
        '\r', 1,
        '"', 13,
        ',', 9,
        ';', 10,
        0x0b, 17,
        '\f', 17,
        ' ', 17,
      );
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '\t', 11,
        '\n', 21,
        '\r', 1,
        '"', 12,
        ',', 9,
        ';', 10,
        0x0b, 17,
        '\f', 17,
        ' ', 17,
      );
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 2:
      if (lookahead == '\t') SKIP(2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '"') ADVANCE(12);
      if (lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != ',' &&
          lookahead != ';') ADVANCE(20);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(13);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(5);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\\') ADVANCE(15);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(12);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r') SKIP(4);
      if (lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != ',' &&
          lookahead != ';') ADVANCE(20);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      END_STATE();
    case 6:
      if (eof) ADVANCE(8);
      ADVANCE_MAP(
        '\t', 11,
        '\n', 21,
        '\r', 1,
        '"', 12,
        ',', 9,
        ';', 10,
        0x0b, 17,
        '\f', 17,
        ' ', 17,
      );
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 7:
      if (eof) ADVANCE(8);
      if (lookahead == '\t') SKIP(7);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '"') ADVANCE(12);
      if (lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != ',' &&
          lookahead != ';') ADVANCE(20);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_TAB);
      if (lookahead == '\t') ADVANCE(11);
      if (lookahead == '\n') ADVANCE(21);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(17);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      if (lookahead == '"') ADVANCE(16);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_quoted_cell_token1);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(14);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(15);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_quoted_cell_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_escaped_quote);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_unquoted_cell);
      ADVANCE_MAP(
        '\t', 11,
        '\n', 21,
        '\r', 1,
        '"', 12,
        ',', 9,
        ';', 10,
        0x0b, 17,
        '\f', 17,
        ' ', 17,
      );
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_unquoted_cell);
      if (lookahead == '\t') SKIP(2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '"') ADVANCE(12);
      if (lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != ',' &&
          lookahead != ';') ADVANCE(20);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_unquoted_cell);
      if (lookahead == '"') ADVANCE(12);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r') SKIP(4);
      if (lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != ',' &&
          lookahead != ';') ADVANCE(20);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_unquoted_cell);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != ',' &&
          lookahead != ';') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_newline);
      if (lookahead == '\t') ADVANCE(11);
      if (lookahead == '\n') ADVANCE(21);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(17);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_newline);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(18);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 7},
  [2] = {.lex_state = 6},
  [3] = {.lex_state = 6},
  [4] = {.lex_state = 6},
  [5] = {.lex_state = 7},
  [6] = {.lex_state = 7},
  [7] = {.lex_state = 6},
  [8] = {.lex_state = 6},
  [9] = {.lex_state = 6},
  [10] = {.lex_state = 6},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 7},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 7},
  [15] = {.lex_state = 4},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 4},
  [18] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_TAB] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escaped_quote] = ACTIONS(1),
    [sym_unquoted_cell] = ACTIONS(1),
    [sym_newline] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(18),
    [sym_record] = STATE(12),
    [sym_cell] = STATE(2),
    [sym_quoted_cell] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(5),
    [sym_unquoted_cell] = ACTIONS(7),
    [sym_newline] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym_delimiter] = STATE(15),
    [aux_sym_record_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(11),
    [anon_sym_COMMA] = ACTIONS(13),
    [anon_sym_SEMI] = ACTIONS(13),
    [anon_sym_TAB] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [sym_unquoted_cell] = ACTIONS(15),
    [sym_newline] = ACTIONS(15),
  },
  [STATE(3)] = {
    [sym_delimiter] = STATE(15),
    [aux_sym_record_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(17),
    [anon_sym_COMMA] = ACTIONS(13),
    [anon_sym_SEMI] = ACTIONS(13),
    [anon_sym_TAB] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(19),
    [sym_unquoted_cell] = ACTIONS(19),
    [sym_newline] = ACTIONS(19),
  },
  [STATE(4)] = {
    [sym_delimiter] = STATE(15),
    [aux_sym_record_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(21),
    [anon_sym_COMMA] = ACTIONS(23),
    [anon_sym_SEMI] = ACTIONS(23),
    [anon_sym_TAB] = ACTIONS(23),
    [anon_sym_DQUOTE] = ACTIONS(26),
    [sym_unquoted_cell] = ACTIONS(26),
    [sym_newline] = ACTIONS(26),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(7), 1,
      sym_unquoted_cell,
    ACTIONS(28), 1,
      ts_builtin_sym_end,
    ACTIONS(30), 1,
      sym_newline,
    STATE(2), 1,
      sym_cell,
    STATE(6), 1,
      aux_sym_source_file_repeat1,
    STATE(7), 1,
      sym_quoted_cell,
    STATE(12), 1,
      sym_record,
  [25] = 8,
    ACTIONS(32), 1,
      ts_builtin_sym_end,
    ACTIONS(34), 1,
      anon_sym_DQUOTE,
    ACTIONS(37), 1,
      sym_unquoted_cell,
    ACTIONS(40), 1,
      sym_newline,
    STATE(2), 1,
      sym_cell,
    STATE(6), 1,
      aux_sym_source_file_repeat1,
    STATE(7), 1,
      sym_quoted_cell,
    STATE(12), 1,
      sym_record,
  [50] = 2,
    ACTIONS(43), 1,
      ts_builtin_sym_end,
    ACTIONS(45), 6,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_TAB,
      anon_sym_DQUOTE,
      sym_unquoted_cell,
      sym_newline,
  [62] = 2,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    ACTIONS(49), 6,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_TAB,
      anon_sym_DQUOTE,
      sym_unquoted_cell,
      sym_newline,
  [74] = 2,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    ACTIONS(53), 6,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_TAB,
      anon_sym_DQUOTE,
      sym_unquoted_cell,
      sym_newline,
  [86] = 2,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(26), 6,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_TAB,
      anon_sym_DQUOTE,
      sym_unquoted_cell,
      sym_newline,
  [98] = 3,
    ACTIONS(55), 1,
      anon_sym_DQUOTE,
    STATE(13), 1,
      aux_sym_quoted_cell_repeat1,
    ACTIONS(57), 2,
      aux_sym_quoted_cell_token1,
      sym_escaped_quote,
  [109] = 3,
    ACTIONS(59), 1,
      ts_builtin_sym_end,
    ACTIONS(63), 1,
      sym_newline,
    ACTIONS(61), 2,
      anon_sym_DQUOTE,
      sym_unquoted_cell,
  [120] = 3,
    ACTIONS(66), 1,
      anon_sym_DQUOTE,
    STATE(16), 1,
      aux_sym_quoted_cell_repeat1,
    ACTIONS(68), 2,
      aux_sym_quoted_cell_token1,
      sym_escaped_quote,
  [131] = 2,
    ACTIONS(32), 1,
      ts_builtin_sym_end,
    ACTIONS(70), 3,
      anon_sym_DQUOTE,
      sym_unquoted_cell,
      sym_newline,
  [140] = 4,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(7), 1,
      sym_unquoted_cell,
    STATE(7), 1,
      sym_quoted_cell,
    STATE(10), 1,
      sym_cell,
  [153] = 3,
    ACTIONS(72), 1,
      anon_sym_DQUOTE,
    STATE(16), 1,
      aux_sym_quoted_cell_repeat1,
    ACTIONS(74), 2,
      aux_sym_quoted_cell_token1,
      sym_escaped_quote,
  [164] = 1,
    ACTIONS(77), 2,
      anon_sym_DQUOTE,
      sym_unquoted_cell,
  [169] = 1,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(5)] = 0,
  [SMALL_STATE(6)] = 25,
  [SMALL_STATE(7)] = 50,
  [SMALL_STATE(8)] = 62,
  [SMALL_STATE(9)] = 74,
  [SMALL_STATE(10)] = 86,
  [SMALL_STATE(11)] = 98,
  [SMALL_STATE(12)] = 109,
  [SMALL_STATE(13)] = 120,
  [SMALL_STATE(14)] = 131,
  [SMALL_STATE(15)] = 140,
  [SMALL_STATE(16)] = 153,
  [SMALL_STATE(17)] = 164,
  [SMALL_STATE(18)] = 169,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [15] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_record, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 2, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_record, 2, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_record_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_record_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [26] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_record_repeat1, 2, 0, 0),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [30] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cell, 1, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cell, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_cell, 2, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_cell, 2, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_cell, 3, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_cell, 3, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0), SHIFT_REPEAT(14),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_cell_repeat1, 2, 0, 0),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_cell_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_delimiter, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_pdx_eu4_csv(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "pdx_eu4_csv",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
