/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 19
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 22
#define ALIAS_COUNT 0
#define TOKEN_COUNT 16
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_localisation_key = 1,
  sym_bom = 2,
  anon_sym_COLON = 3,
  sym_language_identifier = 4,
  sym_version = 5,
  anon_sym_DQUOTE = 6,
  aux_sym_localisation_string_token1 = 7,
  aux_sym_localisation_string_token2 = 8,
  sym_escape_sequence = 9,
  sym_parameter_substitution = 10,
  sym_scope_reference = 11,
  sym_colour_tag = 12,
  sym_unquoted_value = 13,
  sym_comment = 14,
  sym_newline = 15,
  sym_source_file = 16,
  sym_language_header = 17,
  sym_entry = 18,
  sym_localisation_string = 19,
  aux_sym_source_file_repeat1 = 20,
  aux_sym_localisation_string_repeat1 = 21,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_localisation_key] = "localisation_key",
  [sym_bom] = "bom",
  [anon_sym_COLON] = ":",
  [sym_language_identifier] = "language_identifier",
  [sym_version] = "version",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_localisation_string_token1] = "localisation_string_token1",
  [aux_sym_localisation_string_token2] = "localisation_string_token2",
  [sym_escape_sequence] = "escape_sequence",
  [sym_parameter_substitution] = "parameter_substitution",
  [sym_scope_reference] = "scope_reference",
  [sym_colour_tag] = "colour_tag",
  [sym_unquoted_value] = "unquoted_value",
  [sym_comment] = "comment",
  [sym_newline] = "newline",
  [sym_source_file] = "source_file",
  [sym_language_header] = "language_header",
  [sym_entry] = "entry",
  [sym_localisation_string] = "localisation_string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_localisation_string_repeat1] = "localisation_string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_localisation_key] = sym_localisation_key,
  [sym_bom] = sym_bom,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_language_identifier] = sym_language_identifier,
  [sym_version] = sym_version,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_localisation_string_token1] = aux_sym_localisation_string_token1,
  [aux_sym_localisation_string_token2] = aux_sym_localisation_string_token2,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_parameter_substitution] = sym_parameter_substitution,
  [sym_scope_reference] = sym_scope_reference,
  [sym_colour_tag] = sym_colour_tag,
  [sym_unquoted_value] = sym_unquoted_value,
  [sym_comment] = sym_comment,
  [sym_newline] = sym_newline,
  [sym_source_file] = sym_source_file,
  [sym_language_header] = sym_language_header,
  [sym_entry] = sym_entry,
  [sym_localisation_string] = sym_localisation_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_localisation_string_repeat1] = aux_sym_localisation_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_localisation_key] = {
    .visible = true,
    .named = true,
  },
  [sym_bom] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_language_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_version] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_localisation_string_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_localisation_string_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_substitution] = {
    .visible = true,
    .named = true,
  },
  [sym_scope_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_colour_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_unquoted_value] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_language_header] = {
    .visible = true,
    .named = true,
  },
  [sym_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_localisation_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_localisation_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_key = 1,
  field_language = 2,
  field_value = 3,
  field_version = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_language] = "language",
  [field_value] = "value",
  [field_version] = "version",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_language, 0},
  [1] =
    {field_key, 0},
    {field_value, 1},
  [3] =
    {field_key, 0},
    {field_value, 3},
    {field_version, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      ADVANCE_MAP(
        '\n', 33,
        '\r', 1,
        '"', 19,
        '#', 32,
        '$', 24,
        ':', 15,
        '[', 22,
        0xa7, 23,
        0xfeff, 14,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(33);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == '#') ADVANCE(32);
      if (lookahead == ':') ADVANCE(15);
      if (lookahead == 0xfeff) ADVANCE(14);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(33);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '#') ADVANCE(32);
      if (lookahead == 0xfeff) ADVANCE(14);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 3:
      if (lookahead == '\r') SKIP(5);
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == '$') ADVANCE(25);
      if (lookahead == '[') ADVANCE(26);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead == 0xa7) ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(21);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == ':') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '#') ADVANCE(31);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(5);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(6);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '#') ADVANCE(31);
      END_STATE();
    case 7:
      if (lookahead == '$') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == ']') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 10:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(27);
      END_STATE();
    case 11:
      if (eof) ADVANCE(13);
      if (lookahead == '\n') ADVANCE(33);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == '#') ADVANCE(32);
      if (lookahead == ':') ADVANCE(15);
      if (lookahead == 0xfeff) ADVANCE(14);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 12:
      if (eof) ADVANCE(13);
      if (lookahead == '\n') ADVANCE(33);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '#') ADVANCE(32);
      if (lookahead == 0xfeff) ADVANCE(14);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(12);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_bom);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_localisation_key);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_localisation_key);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_version);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_localisation_string_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '[' &&
          lookahead != '\\' &&
          lookahead != 0xa7) ADVANCE(21);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_localisation_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '[' &&
          lookahead != '\\' &&
          lookahead != 0xa7) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_localisation_string_token2);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_localisation_string_token2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_localisation_string_token2);
      if (lookahead == '$' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_localisation_string_token2);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '$') ADVANCE(7);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_localisation_string_token2);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ']') ADVANCE(8);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_parameter_substitution);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_scope_reference);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_colour_tag);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_newline);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'l') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '_') ADVANCE(2);
      END_STATE();
    case 2:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(3);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(sym_language_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(3);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 12},
  [2] = {.lex_state = 12},
  [3] = {.lex_state = 12},
  [4] = {.lex_state = 12},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 12},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 12},
  [10] = {.lex_state = 12},
  [11] = {.lex_state = 12},
  [12] = {.lex_state = 12},
  [13] = {.lex_state = 12},
  [14] = {.lex_state = 4},
  [15] = {.lex_state = 6},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 9},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_localisation_key] = ACTIONS(1),
    [sym_bom] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_language_identifier] = ACTIONS(1),
    [sym_version] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [aux_sym_localisation_string_token2] = ACTIONS(1),
    [sym_colour_tag] = ACTIONS(1),
    [sym_unquoted_value] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_newline] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(17),
    [sym_language_header] = STATE(3),
    [sym_entry] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_localisation_key] = ACTIONS(5),
    [sym_bom] = ACTIONS(7),
    [sym_language_identifier] = ACTIONS(9),
    [sym_comment] = ACTIONS(11),
    [sym_newline] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(5), 1,
      sym_localisation_key,
    ACTIONS(9), 1,
      sym_language_identifier,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 2,
      sym_comment,
      sym_newline,
    STATE(4), 3,
      sym_language_header,
      sym_entry,
      aux_sym_source_file_repeat1,
  [19] = 5,
    ACTIONS(5), 1,
      sym_localisation_key,
    ACTIONS(9), 1,
      sym_language_identifier,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 2,
      sym_comment,
      sym_newline,
    STATE(6), 3,
      sym_language_header,
      sym_entry,
      aux_sym_source_file_repeat1,
  [38] = 5,
    ACTIONS(5), 1,
      sym_localisation_key,
    ACTIONS(9), 1,
      sym_language_identifier,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 2,
      sym_comment,
      sym_newline,
    STATE(6), 3,
      sym_language_header,
      sym_entry,
      aux_sym_source_file_repeat1,
  [57] = 4,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      aux_sym_localisation_string_token2,
    STATE(7), 1,
      aux_sym_localisation_string_repeat1,
    ACTIONS(23), 5,
      aux_sym_localisation_string_token1,
      sym_escape_sequence,
      sym_parameter_substitution,
      sym_scope_reference,
      sym_colour_tag,
  [74] = 5,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(29), 1,
      sym_localisation_key,
    ACTIONS(32), 1,
      sym_language_identifier,
    ACTIONS(35), 2,
      sym_comment,
      sym_newline,
    STATE(6), 3,
      sym_language_header,
      sym_entry,
      aux_sym_source_file_repeat1,
  [93] = 4,
    ACTIONS(38), 1,
      anon_sym_DQUOTE,
    ACTIONS(42), 1,
      aux_sym_localisation_string_token2,
    STATE(8), 1,
      aux_sym_localisation_string_repeat1,
    ACTIONS(40), 5,
      aux_sym_localisation_string_token1,
      sym_escape_sequence,
      sym_parameter_substitution,
      sym_scope_reference,
      sym_colour_tag,
  [110] = 4,
    ACTIONS(44), 1,
      anon_sym_DQUOTE,
    ACTIONS(49), 1,
      aux_sym_localisation_string_token2,
    STATE(8), 1,
      aux_sym_localisation_string_repeat1,
    ACTIONS(46), 5,
      aux_sym_localisation_string_token1,
      sym_escape_sequence,
      sym_parameter_substitution,
      sym_scope_reference,
      sym_colour_tag,
  [127] = 2,
    ACTIONS(54), 2,
      sym_language_identifier,
      sym_localisation_key,
    ACTIONS(52), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym_newline,
  [137] = 2,
    ACTIONS(58), 2,
      sym_language_identifier,
      sym_localisation_key,
    ACTIONS(56), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym_newline,
  [147] = 2,
    ACTIONS(62), 2,
      sym_language_identifier,
      sym_localisation_key,
    ACTIONS(60), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym_newline,
  [157] = 2,
    ACTIONS(66), 2,
      sym_language_identifier,
      sym_localisation_key,
    ACTIONS(64), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym_newline,
  [167] = 2,
    ACTIONS(70), 2,
      sym_language_identifier,
      sym_localisation_key,
    ACTIONS(68), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym_newline,
  [177] = 4,
    ACTIONS(72), 1,
      anon_sym_COLON,
    ACTIONS(74), 1,
      anon_sym_DQUOTE,
    ACTIONS(76), 1,
      sym_unquoted_value,
    STATE(10), 1,
      sym_localisation_string,
  [190] = 3,
    ACTIONS(74), 1,
      anon_sym_DQUOTE,
    ACTIONS(78), 1,
      sym_unquoted_value,
    STATE(12), 1,
      sym_localisation_string,
  [200] = 1,
    ACTIONS(80), 1,
      anon_sym_COLON,
  [204] = 1,
    ACTIONS(82), 1,
      ts_builtin_sym_end,
  [208] = 1,
    ACTIONS(84), 1,
      sym_version,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 19,
  [SMALL_STATE(4)] = 38,
  [SMALL_STATE(5)] = 57,
  [SMALL_STATE(6)] = 74,
  [SMALL_STATE(7)] = 93,
  [SMALL_STATE(8)] = 110,
  [SMALL_STATE(9)] = 127,
  [SMALL_STATE(10)] = 137,
  [SMALL_STATE(11)] = 147,
  [SMALL_STATE(12)] = 157,
  [SMALL_STATE(13)] = 167,
  [SMALL_STATE(14)] = 177,
  [SMALL_STATE(15)] = 190,
  [SMALL_STATE(16)] = 200,
  [SMALL_STATE(17)] = 204,
  [SMALL_STATE(18)] = 208,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [38] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [42] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [44] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_localisation_string_repeat1, 2, 0, 0),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_localisation_string_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_localisation_string_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_language_header, 2, 0, 1),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_language_header, 2, 0, 1),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entry, 2, 0, 2),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_entry, 2, 0, 2),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_localisation_string, 2, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_localisation_string, 2, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entry, 4, 0, 3),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_entry, 4, 0, 3),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_localisation_string, 3, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_localisation_string, 3, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [78] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [82] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_localisation(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_localisation_key,
    .primary_state_ids = ts_primary_state_ids,
    .name = "localisation",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
