//! Lossless, bounded binding specialization for Template text and source dependencies.
use crate::analysis::{AnalysisCoverage, AnalysisLimit, ResidualReason};
use rules::replacement::Template;
use std::collections::{BTreeMap, BTreeSet};

/// One generated source piece and the root binding names that influence it.
#[derive(Clone, Debug)]
pub struct SourcePiece {
    /// Definition owning this range.
    pub origin: (String, String),
    /// Range in generated UTF-8 text.
    pub range: text::TextRange,
    /// Original definition range; binding insertions point at their source use.
    pub definition_range: text::TextRange,
    /// Root bindings read to produce this piece.
    pub parameters: BTreeSet<String>,
    /// Local binding supplying this insertion; guards are separate dependencies.
    pub binding_name: Option<String>,
    /// Exact byte-boundary projection into one root binding, when recoverable.
    pub binding_source: Option<BindingSource>,
    /// The piece represents a missing or editing value.
    pub hole: bool,
}

/// Maps generated byte boundaries into the decoded value of one root argument.
#[derive(Clone, Debug)]
pub struct BindingSource {
    /// Root argument whose bytes supplied this insertion.
    pub parameter: String,
    /// One root byte offset for each generated boundary, including the end boundary.
    pub offsets: std::sync::Arc<[u32]>,
}

/// Specialized source. Source dependencies remain separate from validation and UI ranges.
#[derive(Clone, Debug, Default)]
pub struct RenderedTemplate {
    /// Generated script body, without the declaration's wrapper braces.
    pub text: String,
    /// Relative source/dependency map.
    pub pieces: Vec<SourcePiece>,
    /// Traversal and interpretation coverage.
    pub coverage: AnalysisCoverage,
}

impl RenderedTemplate {
    /// Binding dependencies intersecting a generated range.
    pub fn dependencies(&self, range: text::TextRange) -> BTreeSet<String> {
        self.pieces
            .iter()
            .filter(|piece| {
                (piece.range.start() < range.end() && range.start() < piece.range.end())
                    || (range.is_empty()
                        && piece.range.start() <= range.start()
                        && range.start() <= piece.range.end())
            })
            .flat_map(|piece| piece.parameters.iter().cloned())
            .collect()
    }
    /// Whether a generated range contains unresolved input.
    pub fn has_hole(&self, range: text::TextRange) -> bool {
        self.pieces.iter().any(|piece| {
            piece.hole && (piece.range.start() < range.end() && range.start() < piece.range.end())
                || (range.is_empty()
                    && piece.range.start() <= range.start()
                    && range.start() <= piece.range.end())
        })
    }
}

/// Renders the adopted one-pass text profile. Inserted markers retain interpretation uncertainty.
pub fn render(
    template: &Template,
    bindings: &BTreeMap<String, String>,
    present: &BTreeSet<String>,
    byte_limit: usize,
) -> RenderedTemplate {
    render_with_views(
        template,
        bindings,
        present,
        &BTreeMap::new(),
        &BTreeSet::new(),
        byte_limit,
    )
}

fn render_with_views(
    template: &Template,
    bindings: &BTreeMap<String, String>,
    present: &BTreeSet<String>,
    raw: &BTreeMap<String, String>,
    scalar_uses: &BTreeSet<u32>,
    byte_limit: usize,
) -> RenderedTemplate {
    let mut output = RenderedTemplate::default();
    if template.source.is_empty() {
        output
            .coverage
            .limits
            .insert(AnalysisLimit::UnavailableTemplate);
        return output;
    }
    let source = template.source.as_ref();
    let start = usize::from(source.starts_with('{'));
    let end = source.len() - usize::from(source.ends_with('}'));
    let Some(source) = source.get(start..end) else {
        output
            .coverage
            .limits
            .insert(AnalysisLimit::StructuralRecovery);
        return output;
    };
    let mut offset = 0;
    let mut guards = Vec::new();
    let mut active = true;
    let mut quoted = false;
    let mut comment = false;
    let mut escaped = false;
    let mut steps = 0;
    while offset < source.len() {
        steps += 1;
        if steps > 1_000_000 {
            output.coverage.limits.insert(AnalysisLimit::Nodes);
            break;
        }
        let remaining = &source[offset..];
        if !quoted && !comment && remaining.starts_with("[[") {
            let Some(close) = remaining.find(']') else {
                output
                    .coverage
                    .limits
                    .insert(AnalysisLimit::StructuralRecovery);
                break;
            };
            let condition = &remaining[2..close];
            let (negated, name) = condition
                .strip_prefix('!')
                .map_or((false, condition), |name| (true, name));
            guards.push((active, name.to_ascii_lowercase()));
            active &= present.contains(&name.to_ascii_lowercase()) != negated;
            offset += close + 1;
            continue;
        }
        if !quoted && !comment && remaining.starts_with(']') && !guards.is_empty() {
            active = guards.pop().is_some_and(|(previous, _)| previous);
            offset += 1;
            continue;
        }
        let mut dependencies = guards
            .iter()
            .map(|(_, name)| name.clone())
            .collect::<BTreeSet<_>>();
        let mut binding_name = None;
        let (value, next, hole) = if !comment && remaining.starts_with('$') {
            let Some(close) = remaining[1..].find('$').map(|i| i + 1) else {
                output
                    .coverage
                    .limits
                    .insert(AnalysisLimit::StructuralRecovery);
                break;
            };
            let name = remaining[1..close].to_ascii_lowercase();
            dependencies.insert(name.clone());
            binding_name = Some(name.clone());
            escaped = false;
            match bindings.get(&name) {
                Some(value) => {
                    if value.contains('$') {
                        output
                            .coverage
                            .residuals
                            .insert(ResidualReason::TextInterpretation);
                    }
                    let supplied = raw.get(&name);
                    let value = if quoted {
                        supplied
                            .and_then(|text| {
                                text.strip_prefix('"')
                                    .and_then(|text| text.strip_suffix('"'))
                            })
                            .unwrap_or(value)
                    } else if scalar_uses
                        .contains(&(template.body_range.start() + start as u32 + offset as u32))
                    {
                        supplied.unwrap_or(value).as_str()
                    } else {
                        value.as_str()
                    };
                    (std::borrow::Cow::Borrowed(value), offset + close + 1, false)
                }
                None => {
                    output.coverage.residuals.insert(ResidualReason::Binding);
                    (
                        std::borrow::Cow::Owned(format!("__pdc_hole_{name}")),
                        offset + close + 1,
                        true,
                    )
                }
            }
        } else {
            let Some(ch) = remaining.chars().next() else {
                break;
            };
            if comment {
                comment = ch != '\n';
            } else if quoted {
                if escaped {
                    escaped = false;
                } else if ch == '\\' {
                    escaped = true;
                } else if ch == '"' {
                    quoted = false;
                }
            } else if ch == '#' {
                comment = true;
            } else if ch == '"' {
                quoted = true;
            }
            (
                std::borrow::Cow::Borrowed(&source[offset..offset + ch.len_utf8()]),
                offset + ch.len_utf8(),
                false,
            )
        };
        if active {
            if value.len() > byte_limit.saturating_sub(output.text.len()) {
                output.coverage.limits.insert(AnalysisLimit::TextBytes);
                break;
            }
            let from = output.text.len();
            output.text.push_str(&value);
            let range = text::TextRange::new(from as u32, output.text.len() as u32)
                .expect("bounded text range");
            let origin = text::TextRange::new(
                template.body_range.start() + start as u32 + offset as u32,
                template.body_range.start() + start as u32 + next as u32,
            )
            .unwrap_or(template.body_range);
            if let Some(previous) = output.pieces.last_mut()
                && binding_name.is_none()
                && previous.binding_name.is_none()
                && previous.parameters == dependencies
                && !previous.hole
                && previous.definition_range.end() == origin.start()
            {
                previous.range = text::TextRange::new(previous.range.start(), range.end())
                    .expect("ordered piece range");
                previous.definition_range =
                    text::TextRange::new(previous.definition_range.start(), origin.end())
                        .expect("ordered source range");
            } else {
                output.pieces.push(SourcePiece {
                    origin: (template.kind.to_string(), template.name.clone()),
                    range,
                    definition_range: origin,
                    parameters: dependencies,
                    binding_name,
                    binding_source: None,
                    hole,
                });
            }
        }
        offset = next;
    }
    if !guards.is_empty() {
        output
            .coverage
            .limits
            .insert(AnalysisLimit::StructuralRecovery);
    }
    output
}

fn scalar_use_positions(
    ir: &rules::ir::RulesIr,
    template: &Template,
    bindings: &BTreeMap<String, String>,
    schema: rules::ir::SchemaId,
) -> BTreeSet<u32> {
    use rules::replacement::{TemplateFragment, TemplateInstruction, TemplateOperand};
    let mut result = BTreeSet::new();
    let mut pending = vec![(0, schema)];
    while let Some((block, schema)) = pending.pop() {
        for instruction in template.program.blocks[block].iter() {
            match instruction {
                TemplateInstruction::When { block, .. } => pending.push((*block, schema)),
                TemplateInstruction::Dispatch(property) => {
                    let key = property
                        .key
                        .fragments
                        .iter()
                        .map(|part| match part {
                            TemplateFragment::Literal(text) => Some(text.as_str()),
                            TemplateFragment::Parameter { name, .. } => {
                                bindings.get(&name.to_ascii_lowercase()).map(String::as_str)
                            }
                        })
                        .collect::<Option<Vec<_>>>()
                        .map(|parts| parts.concat());
                    let Some(key) = key else {
                        continue;
                    };
                    let fields=ir.fields(schema).into_iter().filter(|id|matches!(ir.matcher(ir.field(*id).key),rules::ir::Matcher::Literal(name) if ir.strings().resolve(*name).eq_ignore_ascii_case(&key))).collect::<Vec<_>>();
                    match &property.value {
                        TemplateOperand::Scalar(token)
                            if !token.quoted
                                && token.fragments.len() == 1
                                && fields.iter().any(|id| {
                                    matches!(ir.field(*id).value, rules::ir::FieldValue::Scalar(_))
                                }) =>
                        {
                            result.insert(token.range.start());
                        }
                        TemplateOperand::Block(block) => {
                            for id in fields {
                                if let Some(child) = ir.child(id, schema) {
                                    pending.push((*block, child));
                                }
                            }
                        }
                        _ => {}
                    }
                }
                _ => {}
            }
        }
    }
    result
}

fn append_slice(
    target: &mut RenderedTemplate,
    source: &RenderedTemplate,
    range: text::TextRange,
    extra: &BTreeSet<String>,
    limit: usize,
) -> bool {
    let Some(text) = source
        .text
        .get(range.start() as usize..range.end() as usize)
    else {
        return false;
    };
    if text.len() > limit.saturating_sub(target.text.len()) {
        target.coverage.limits.insert(AnalysisLimit::TextBytes);
        return false;
    }
    let shift = target.text.len() as i64 - range.start() as i64;
    target.text.push_str(text);
    for piece in source
        .pieces
        .iter()
        .filter(|piece| piece.range.start() < range.end() && range.start() < piece.range.end())
    {
        let mut piece = piece.clone();
        let start = piece.range.start().max(range.start());
        let end = piece.range.end().min(range.end());
        if let Some(mapping) = &mut piece.binding_source {
            mapping.offsets = mapping
                .offsets
                .get((start - piece.range.start()) as usize..=(end - piece.range.start()) as usize)
                .map(std::sync::Arc::from)
                .unwrap_or_else(|| std::sync::Arc::from([]));
        }
        piece.range =
            text::TextRange::new((start as i64 + shift) as u32, (end as i64 + shift) as u32)
                .expect("ordered slice projection");
        piece.parameters.extend(extra.iter().cloned());
        target.pieces.push(piece);
    }
    target.coverage.merge(&source.coverage);
    true
}

enum RenderTask {
    Exit(String),
    Enter {
        template: std::sync::Arc<Template>,
        bindings: BTreeMap<String, String>,
        raw: BTreeMap<String, String>,
        present: BTreeSet<String>,
        root_names: BTreeMap<String, BTreeSet<String>>,
        binding_sources: BTreeMap<String, BindingSource>,
        influence: BTreeSet<String>,
        schema: rules::ir::SchemaId,
        state: Box<crate::ScopeState>,
    },
    Emit {
        source: std::sync::Arc<RenderedTemplate>,
        range: text::TextRange,
        influence: BTreeSet<String>,
    },
}

/// Materializes a bounded concrete/partial Template container for structural checking.
/// Calls are identified by ordinary rule selection, not by matching arbitrary key strings.
#[allow(clippy::too_many_arguments)]
pub fn render_expanded<E>(
    ir: &rules::ir::RulesIr,
    facts: &dyn rules::ir::SymbolFacts,
    template: std::sync::Arc<Template>,
    bindings: &BTreeMap<String, String>,
    raw: &BTreeMap<String, String>,
    present: &BTreeSet<String>,
    schema: rules::ir::SchemaId,
    state: crate::ScopeState,
    byte_limit: usize,
    checkpoint: &mut dyn FnMut() -> Result<(), E>,
) -> Result<RenderedTemplate, E> {
    let mut output = RenderedTemplate::default();
    if bindings.values().any(|value| value.len() > byte_limit)
        || raw.values().any(|value| value.len() > byte_limit)
    {
        output.coverage.limits.insert(AnalysisLimit::TextBytes);
        return Ok(output);
    }
    let mut work = vec![RenderTask::Enter {
        template,
        bindings: bindings.clone(),
        raw: raw.clone(),
        present: present.clone(),
        root_names: bindings
            .keys()
            .chain(present.iter())
            .map(|name| (name.clone(), BTreeSet::from([name.clone()])))
            .collect(),
        binding_sources: bindings
            .iter()
            .map(|(name, value)| {
                (
                    name.clone(),
                    BindingSource {
                        parameter: name.clone(),
                        offsets: std::sync::Arc::from((0..=value.len() as u32).collect::<Vec<_>>()),
                    },
                )
            })
            .collect(),
        influence: BTreeSet::new(),
        schema,
        state: Box::new(state),
    }];
    let mut frames = 0;
    let mut processed_bytes = 0usize;
    let mut visiting = std::collections::HashSet::new();
    while let Some(task) = work.pop() {
        checkpoint()?;
        match task {
            RenderTask::Exit(identity) => {
                visiting.remove(&identity);
            }
            RenderTask::Emit {
                source,
                range,
                influence,
            } => {
                if !append_slice(&mut output, &source, range, &influence, byte_limit) {
                    break;
                }
            }
            RenderTask::Enter {
                template,
                bindings,
                raw,
                present,
                root_names,
                binding_sources,
                influence,
                schema,
                state,
            } => {
                let state = *state;
                frames += 1;
                if frames > 100_000 {
                    output.coverage.limits.insert(AnalysisLimit::Nodes);
                    break;
                }
                let identity = format!(
                    "{}:{}:{bindings:?}:{present:?}:{state:?}",
                    template.kind, template.name
                );
                if !visiting.insert(identity.clone()) {
                    output.coverage.limits.insert(AnalysisLimit::RecursiveState);
                    break;
                }
                work.push(RenderTask::Exit(identity));
                let scalar_uses = scalar_use_positions(ir, &template, &bindings, schema);
                let mut rendered = render_with_views(
                    &template,
                    &bindings,
                    &present,
                    &raw,
                    &scalar_uses,
                    byte_limit,
                );
                for piece in &mut rendered.pieces {
                    if let Some(name) = &piece.binding_name
                        && let (Some(binding), Some(value)) =
                            (binding_sources.get(name), bindings.get(name))
                    {
                        let generated = &rendered.text
                            [piece.range.start() as usize..piece.range.end() as usize];
                        let raw = raw.get(name);
                        let decoded = raw.and_then(|raw| parser::decode_quoted_script(raw));
                        let offsets = if generated == value {
                            Some((0..=generated.len() as u32).collect::<Vec<_>>())
                        } else if raw.is_some_and(|raw| raw == generated) {
                            decoded.as_ref().map(|decoded| {
                                (0..=generated.len() as u32)
                                    .filter_map(|i| decoded.1.source_offset(i))
                                    .collect::<Vec<_>>()
                            })
                        } else if raw.is_some_and(|raw| {
                            raw.strip_prefix('"').and_then(|raw| raw.strip_suffix('"'))
                                == Some(generated)
                        }) {
                            decoded.as_ref().map(|decoded| {
                                (0..=generated.len() as u32)
                                    .filter_map(|i| decoded.1.source_offset(i + 1))
                                    .collect::<Vec<_>>()
                            })
                        } else {
                            None
                        };
                        if let Some(offsets) = offsets
                            && offsets.len() == generated.len() + 1
                        {
                            let mapped = offsets
                                .iter()
                                .map(|i| binding.offsets.get(*i as usize).copied())
                                .collect::<Option<Vec<_>>>();
                            if let Some(offsets) = mapped {
                                piece.binding_source = Some(BindingSource {
                                    parameter: binding.parameter.clone(),
                                    offsets: offsets.into(),
                                });
                            }
                        }
                    }

                    piece.parameters = piece
                        .parameters
                        .iter()
                        .flat_map(|name| {
                            root_names
                                .get(name)
                                .cloned()
                                .unwrap_or_else(|| BTreeSet::from([name.clone()]))
                        })
                        .collect();
                    piece.parameters.extend(influence.iter().cloned());
                }
                processed_bytes = processed_bytes.saturating_add(rendered.text.len());
                if processed_bytes > byte_limit.saturating_mul(16) {
                    output.coverage.limits.insert(AnalysisLimit::TextBytes);
                    break;
                }
                output.coverage.merge(&rendered.coverage);
                let parsed =
                    std::sync::Arc::new(parser::parse(parser::FileFormat::Script, &rendered.text));
                let hir = crate::lower_ir_schema(
                    parsed,
                    ir,
                    schema,
                    Default::default(),
                    state.clone(),
                    facts,
                );
                let mut calls = Vec::new();
                let mut covered = Vec::<text::TextRange>::new();
                for property in hir.properties() {
                    checkpoint()?;
                    if covered.iter().any(|range| {
                        range.start() <= property.range.start()
                            && property.range.end() <= range.end()
                    }) {
                        continue;
                    }
                    let Some(field) = hir.field_fact_at(property.key_range) else {
                        continue;
                    };
                    let Some(kind) = field
                        .fields
                        .iter()
                        .find_map(|id| crate::template::template_kind(ir, ir.field(*id).key))
                    else {
                        continue;
                    };
                    let Some(type_id) = ir.type_by_name(&kind) else {
                        continue;
                    };
                    let Some(callee) = facts.replacement_template(type_id, &property.key) else {
                        continue;
                    };
                    let Some(body) = crate::template::template_body(ir, type_id) else {
                        continue;
                    };
                    let parent = hir
                        .schema_facts()
                        .iter()
                        .filter(|parent| {
                            parent.schema == field.schema
                                && parent.range.start() <= property.key_range.start()
                                && property.key_range.end() <= parent.range.end()
                        })
                        .min_by_key(|parent| parent.range.len());
                    let scope = parent.map_or_else(|| state.clone(), |parent| parent.state.clone());
                    let mut child_bindings = BTreeMap::new();
                    let mut child_raw = BTreeMap::new();
                    let mut child_present = BTreeSet::new();
                    let mut child_roots = BTreeMap::new();
                    let mut child_sources = BTreeMap::new();
                    for argument in hir.properties().iter().filter(|argument| {
                        argument.path.len() == property.path.len() + 1
                            && argument.path.starts_with(&property.path)
                            && property.range.start() <= argument.range.start()
                            && argument.range.end() <= property.range.end()
                    }) {
                        let name = argument.key.to_ascii_lowercase();
                        child_present.insert(name.clone());
                        let Some(value) = &argument.scalar else {
                            continue;
                        };
                        let roots = rendered.dependencies(value.range);
                        if !rendered.has_hole(value.range) {
                            child_bindings.insert(
                                name.clone(),
                                crate::template::binding_value(hir.syntax(), value),
                            );
                            child_present.insert(name.clone());
                            if let Some(raw) = rendered
                                .text
                                .get(value.range.start() as usize..value.range.end() as usize)
                            {
                                child_raw.insert(name.clone(), raw.to_owned());
                            }
                        }
                        let decoded = rendered
                            .text
                            .get(value.range.start() as usize..value.range.end() as usize)
                            .filter(|_| value.quoted)
                            .and_then(parser::decode_quoted_script);
                        let mut projection = Vec::new();
                        let mut root = None;
                        let logical = crate::template::binding_value(hir.syntax(), value);
                        for i in 0..=logical.len() as u32 {
                            let relative = decoded
                                .as_ref()
                                .and_then(|decoded| decoded.1.decoded_offset(i))
                                .unwrap_or(i);
                            let absolute = value.range.start() + relative;
                            let point = rendered.pieces.iter().find_map(|piece| {
                                if piece.range.start() <= absolute && absolute <= piece.range.end()
                                {
                                    let map = piece.binding_source.as_ref()?;
                                    Some((
                                        map.parameter.as_str(),
                                        *map.offsets
                                            .get((absolute - piece.range.start()) as usize)?,
                                    ))
                                } else {
                                    None
                                }
                            });
                            let Some((parameter, offset)) = point else {
                                projection.clear();
                                break;
                            };
                            if root.as_deref().is_some_and(|known| known != parameter) {
                                projection.clear();
                                break;
                            }
                            root = Some(parameter.to_owned());
                            projection.push(offset);
                        }
                        if projection.len() == logical.len() + 1
                            && let Some(parameter) = root
                        {
                            child_sources.insert(
                                name.clone(),
                                BindingSource {
                                    parameter,
                                    offsets: projection.into(),
                                },
                            );
                        }
                        child_roots.insert(name, roots);
                    }
                    let mut child_influence = influence.clone();
                    child_influence.extend(rendered.dependencies(property.key_range));
                    calls.push((
                        property.range,
                        RenderTask::Enter {
                            template: callee,
                            bindings: child_bindings,
                            raw: child_raw,
                            present: child_present,
                            root_names: child_roots,
                            binding_sources: child_sources,
                            influence: child_influence,
                            schema: body,
                            state: Box::new(scope),
                        },
                    ));
                    covered.push(property.range);
                }
                calls.sort_by_key(|(range, _)| range.start());
                let rendered = std::sync::Arc::new(rendered);
                let mut tasks = Vec::new();
                let mut from = 0;
                for (range, call) in calls {
                    tasks.push(RenderTask::Emit {
                        source: rendered.clone(),
                        range: text::TextRange::new(from, range.start())
                            .expect("ordered call prefix"),
                        influence: influence.clone(),
                    });
                    tasks.push(call);
                    from = range.end();
                }
                tasks.push(RenderTask::Emit {
                    source: rendered.clone(),
                    range: text::TextRange::new(from, rendered.text.len() as u32)
                        .expect("call suffix"),
                    influence,
                });
                work.extend(tasks.into_iter().rev());
            }
        }
    }
    Ok(output)
}
