[package]
name = "pdx-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "CLI entry points for ParadoxCode."
authors.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
publish = false

[dependencies]
pdx-game = { path = "../pdx-game" }
pdx-game-eu4 = { path = "../pdx-game-eu4" }
pdx-lsp = { path = "../pdx-lsp" }
pdx-rules = { path = "../pdx-rules" }
pdx-workspace = { path = "../pdx-workspace" }

[[bin]]
name = "pdx"
path = "src/bin/pdx.rs"

[[bin]]
name = "pdx-ls"
path = "src/bin/pdx-ls.rs"

[lints]
workspace = true

[dev-dependencies]
tempfile = "3"
