[package]
name = "pdx-fuzz"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
libfuzzer-sys = "0.4"
pdx-format = { path = "../crates/pdx-format" }
pdx-game-eu4 = { path = "../crates/pdx-game-eu4" }
pdx-hir = { path = "../crates/pdx-hir" }
pdx-rules = { path = "../crates/pdx-rules" }
pdx-syntax = { path = "../crates/pdx-syntax" }
pdx-text = { path = "../crates/pdx-text" }

[[bin]]
name = "parse-script"
path = "fuzz_targets/parse_script.rs"
test = false
doc = false
bench = false

[[bin]]
name = "parse-localisation"
path = "fuzz_targets/parse_localisation.rs"
test = false
doc = false
bench = false

[[bin]]
name = "incremental-edits"
path = "fuzz_targets/incremental_edits.rs"
test = false
doc = false
bench = false

[[bin]]
name = "format-script"
path = "fuzz_targets/format_script.rs"
test = false
doc = false
bench = false

[[bin]]
name = "lower-hir"
path = "fuzz_targets/lower_hir.rs"
test = false
doc = false
bench = false
